name: Retrain CAi

on:
  workflow_dispatch:
  push:
    paths:
      - "data/**"

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google creds file
        run: |
          echo "${{ secrets.GOOGLE_CREDS_JSON }}" > google-creds.json

      - name: Pull sheet -> update data/labels.csv
        env:
          GOOGLE_CREDS_JSON: google-creds.json
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/sheet_to_csv.py

      - name: Run retrain
        env:
          DATA_PATH: data/labels.csv
        run: |
          python scripts/retrain.py

      - name: Push model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -m pip install huggingface_hub
          python scripts/push_to_hf.py --model-dir out_model --repo "your-hf-username/CAi-invoice-model"
