name: Retrain CAi

on:
  workflow_dispatch:   # manually run karne ke liye
  push:
    paths:
      - "data/**"      # agar data folder me kuch change hoga to ye run hoga

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub gspread oauth2client

      - name: Write Google credentials to file
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          echo "$GOOGLE_CREDS_JSON" > creds.json

      - name: Pull data from Google Sheets
        run: |
          python scripts/sheet_to_csv.py --creds creds.json --out data/labels.csv

      - name: Run training
        run: |
          python scripts/retrain.py --data data/labels.csv --out out_model

      - name: Push model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -m pip install huggingface_hub
          python scripts/push_to_hf.py --model-dir out_model --repo "shekharbislaji/CAi-Tax-Made-Easy"
